dist: trusty

language: c

sudo: required
services:
 - docker

compiler:
 - gcc
 - clang
 
env:
 - CRYPT=sodium
 - CRYPT=tweetnacl
 - CRYPT=mbedtls

before_install:
 - docker pull ubuntu:artful
 - docker run -it -d -v ${TRAVIS_BUILD_DIR}/..:/mnt  --name build ubuntu:artful bash
 - docker exec build ls -al /mnt
 - docker exec build ls -al /mnt/libcose
 - docker exec build apt-get update
 - docker exec build apt-get --yes install build-essential cmake cmake-data pkg-config libcunit1-dev libsodium-dev llvm clang clang-tidy libmbedtls-dev git
 - docker exec build git clone https://github.com/cabo/cn-cbor /mnt/cn-cbor
 - docker exec build mkdir /mnt/cn-cbor/build
 - docker exec -i build bash -c 'cd /mnt/cn-cbor/build && cmake -Duse_context=on .. && make all'
 - docker exec build git clone https://github.com/RIOT-OS/tweetnacl /mnt/tweetnacl

script:
 - docker exec build bash -c "cd /mnt/libcose && make clean clang-tidy CRYPTO=$CRYPT CC=$CC CBOR_ROOT=/mnt/cn-cbor"
 - docker exec build bash -c "cd /mnt/libcose && make clean test CRYPTO=$CRYPT CC=$CC CBOR_ROOT=/mnt/cn-cbor MBEDTLS_LIB=/usr/lib/x86_64-linux-gnu/libmbedcrypto.so"
